# Configuration for running isodatetime tests on Travis CI
# See https://travis-ci.org/ for more info.

---
language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install pep8
script:
    - python -m isodatetime.tests
    - pep8 -v isodatetime
